name: yeogijeogi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  go_router: ^14.8.1
  provider: ^6.1.2
  sign_in_with_apple: ^6.1.4
  flutter_svg: ^2.0.17
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.1
  flutter_naver_map: ^1.3.0+1
  smooth_page_indicator: ^1.2.1
  location: ^8.0.0
  permission_handler: ^12.0.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/animations/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
